version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    assignees:
      - 'celsodias12'
    labels:
      - 'npm'
    open-pull-requests-limit: 10
    reviewers:
      - 'celsodias12'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    assignees:
      - 'celsodias12'
    labels:
      - 'npm'
    open-pull-requests-limit: 10
    reviewers:
      - 'celsodias12'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    assignees:
      - 'celsodias12'
    labels:
      - 'npm'
    open-pull-requests-limit: 10
    reviewers:
      - 'celsodias12'
